version: '3'

services:
  shop:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/projects/myshopline
    depends_on:
      - redis
      - bananadb
    links:
      - bananadb
  redis:
    image: redis
  bananadb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
