version: '3'

services:
  shop:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/projects/myshopline
    depends_on:
      - redis
      - bananadb
      - es01
    links:
      - bananadb
      - es01
  redis:
    image: redis
  bananadb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
  es01:
    image: elasticsearch:7.14.2
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
    volumes:
      - esdb:/usr/share/elasticsearch/data

volumes:
  mongodb:
  esdb:
